version: 0.2

phases:
  pre_build:
    commands:
      - mvn install -Dmaven.test.skip=true 
  post_build:
    commands:
      - mvn package -Dmaven.test.skip=true 
artifacts:
  files:
    - target/springelastic-0.0.1-SNAPSHOT.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
